# -*- coding: utf-8 -*-
"""TASK2: BMI CALCULATOR

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1KAkO4L_jCWygq12EFBZzqYzECq3y2G5D

## TASK2 : BMI CALCULATOR
"""

# Prompt user for weight and height
weight = float(input("Please enter your weight (in kilograms): "))
height = float(input("Please enter your height (in centimeters): "))

# Convert height to meters
height_in_meters = height / 100

# Calculate BMI (Body Mass Index)
BMI = weight / (height_in_meters ** 2)

# Print BMI
print("Your BMI is:", BMI)

# Determine weight category based on BMI
if BMI < 16:
    print("Your BMI indicates that you are severely underweight.")
elif 16 <= BMI < 18.5:
    print("Your BMI indicates that you are underweight.")
elif 18.5 <= BMI < 24:
    print("Your BMI indicates that you have a healthy weight.")
elif 25 <= BMI < 30:
    print("Your BMI indicates that you are overweight.")
elif BMI >= 30:
    print("Your BMI indicates that you are obese.")