# -*- coding: utf-8 -*-
"""TASK3 : RANDOM PASSWORD GENERATOR.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/100mpZpyV2Nzae_1y1ZpWMZnzaCwvEM0A
"""

import random
import string

# Prompt the user to specify the desired length of the password
length = int(input("Enter the length of the password: "))

# Ask the user whether they want to include letters, numbers, and symbols in the password
include_letters = input("Do you want to include letters? (yes/no): ").lower() == 'yes'
include_numbers = input("Do you want to include numbers? (yes/no): ").lower() == 'yes'
include_symbols = input("Do you want to include symbols? (yes/no): ").lower() == 'yes'

# Define an empty string to store characters for the password
characters = ""

# Check if the user wants to include letters and add them to the characters string if requested
if include_letters:
    characters += string.ascii_letters

# Check if the user wants to include numbers and add them to the characters string if requested
if include_numbers:
    characters += string.digits

# Check if the user wants to include symbols and add them to the characters string if requested
if include_symbols:
    characters += string.punctuation

# Check if at least one character set is selected
if not characters:
    print("Please select at least one character set.")
else:
    # Generate a random password of the specified length using characters from the characters string
    password = ''.join(random.choice(characters) for _ in range(length))

    # Display the generated password to the user
    print("Generated Password:", password)